name: "flattener"

services:
  backend:
    build:
      context: .
      target: dev
    tty: true
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:${HOST_IP:-127.0.0.0}"
    volumes:
      - ./:/app
      - vendor:/app/vendor
      - ./docker/x-php.ini:/usr/local/etc/php/conf.d/x-php.ini
    working_dir: /app
    entrypoint: php -S 0.0.0.0:8000 ./docs/sample.php

volumes:
  vendor: